config/routes.rb
Cartracker::Application.routes.draw do
  devise_for :users

  resources :cars do
	resources :repairs
  end
  
  root to: 'cars#index'












end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :make, :model, :year, :vehicle_type
  
  has_many :repairs
  
end

app/models/repair.rb
class Repair < ActiveRecord::Base
  attr_accessible :car_id, :cost, :date, :mileage, :shop, :work_done
  
  belongs_to :car
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  respond_to :html, :xml, :json
  # GET /repairs
  # GET /repairs.json
  def index
    @car = Car.find(params[:car_id])
	@repairs = @car.repairs

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @repairs }
    end
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
	@car = Car.find(params[:car_id])
    @repair = @car.repairs.build
	respond_with(@repair)


    #respond_to do |format|
    #  format.html # show.html.erb
    #  format.json { render json: @repair }
    #end
  end

  # GET /repairs/new
  # GET /repairs/new.json
  def new
  	@car = Car.find(params[:car_id])
    @repair = @car.repairs.build
	respond_with(@repair)
	
    #@repair = Repair.new

    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.json { render json: @repair }
    #end
  end

  # GET /repairs/1/edit
  def edit
	@car = Car.find(params[:car_id])
	@repair = Repair.find(params[:id])
	respond_with(@repair)
  end

  # POST /repairs
  # POST /repairs.json
  def create
  	@car = Car.find(params[:car_id])
    @repair = @car.repairs.build
	respond_with(@repair)

    #respond_to do |format|
    #  if @car.repair.save
    #    format.html { redirect_to @repair, notice: 'Repair was successfully created.' }
    #    format.json { render json: @repair, status: :created, location: @repair }
    #  else
    #    format.html { render action: "new" }
    #    format.json { render json: @repair.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PUT /repairs/1
  # PUT /repairs/1.json
  def update
	@repair = Repair.find(params[:id])	
	@car = Car.find(params[:car_id])

    respond_to do |format|
      if @repair.update_attributes(params[:repair])
        format.html { redirect_to @repair, notice: 'Repair was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @car = Car.find(params[:car_id])
    @repair = @car.repairs.find(params[:id])
    @repair.destroy
	redirect_to car_path(@car)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<%= f.label :year %>
	<%= f.number_field :year %>
  </div>
  <div class="field">
	<%= f.label :vehicle_type %>
	<%= f.text_field :vehicle_type %>
  </div>
  <div class="field">
	<%= f.label :make %>
	<%= f.text_field :make %>
  </div>
  <div class="field">
	<%= f.label :model %>
	<%= f.text_field :model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>Year</th>
    <th>Make</th>
    <th>Model</th>
	<th>Type</th>
  </tr>

<% @cars.each do |car| %>
  <tr>
	<td><%= car.year %></td>
	<td><%= car.make %></td>
	<td><%= car.model %></td>
	<td><%= car.vehicle_type %></td>
    <td><%= link_to 'Show', car %> | </td>
    <td><%= link_to 'Edit', edit_car_path(car) %> | </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= "#{@car.year} #{@car.make} #{@car.model}" %></h1>

<h2>Repair Log</h2>
<%= render @car.repairs %>

<%= render "repairs/form" %>

<%= link_to 'Edit Car', edit_car_path(@car) %> |
<%= link_to 'Back to car list', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cartracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/repairs/_form.html.erb
<%= form_for ([@car, @car.repairs.build]) do |f| %>

  <h2>Add a repair:</h2>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :shop %><br />
    <%= f.text_field :shop %>
  </div>
  <div class="field">
    <%= f.label :work_done %><br />
    <%= f.text_field :work_done %>
  </div>
  <div class="field">
    <%= f.label :mileage %><br />
    <%= f.number_field :mileage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repairs/_repair.html.erb
<tr>
	<td><%= repair.date %></td>
	<td><%= repair.cost %></td>
	<td><%= repair.shop %></td>
	<td><%= repair.work_done %></td>
	<td><%= repair.mileage %></td>
    <td><%= link_to 'Delete', [repair.car, repair], method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<br />
</tr>

app/views/repairs/edit.html.erb
<h1>Editing repair</h1>

<%= render 'form' %>

app/views/repairs/index.html.erb
<h1>Listing repairs</h1>

<table>
  <tr>
    <th>Car ID</th>
    <th>Date</th>
    <th>Cost</th>
    <th>Shop</th>
    <th>Work done</th>
    <th>Mileage</th>
  </tr>

<% @repairs.each do |repair| %>
  <tr>
    <td><%= repair.car_id %></td>
    <td><%= repair.date %></td>
    <td><%= repair.cost %></td>
    <td><%= repair.shop %></td>
    <td><%= repair.work_done %></td>
    <td><%= repair.mileage %></td>
	<td><%= link_to 'Edit Repair',  edit_car_repair_path(@car) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/repairs/new.html.erb
<h1>New repair</h1>

<%= render 'form' %>

<%= link_to 'Back', car_repairs_path %>

app/views/repairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Car:</b>
  <%= @repair.car_id %>
</p>

<p>
  <b>Date:</b>
  <%= @repair.date %>
</p>

<p>
  <b>Cost:</b>
  <%= @repair.cost %>
</p>

<p>
  <b>Shop:</b>
  <%= @repair.shop %>
</p>

<p>
  <b>Work done:</b>
  <%= @repair.work_done %>
</p>

<p>
  <b>Mileage:</b>
  <%= @repair.mileage %>
</p>